
// Ultra-Industrial Next.js Config
// Author: Ledjan Ahmati

import fs from 'fs'
import path from 'path'

// Lexo konfigurimin industrial nga industrial.config.json
const industrialConfigPath = path.join(__dirname, 'industrial.config.json')
let industrialConfig = {}
try {
  industrialConfig = JSON.parse(fs.readFileSync(industrialConfigPath, 'utf-8'))
} catch (err) {
  console.warn('[Industrial Config] Nuk u lexua dot industrial.config.json:', err)
}

/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  swcMinify: true,
  poweredByHeader: false,
  serviceAnalysis: {
    summary: 'Analiza industriale e tÃ« gjitha shÃ«rbimeve tÃ« frontend/backend',
    services: [
      {
        name: 'Neural Synthesis',
        type: 'krijuese',
        description: 'Sintetizon tÃ« dhÃ«na neurale nÃ« audio industriale',
        endpoints: ['/api/neural-synthesis-data'],
        status: 'active',
        metrics: ['fidelity', 'synthesisTimeMs', 'inputPeak', 'outputPeak']
      },
      {
        name: 'EEG Analysis',
        type: 'studiuese',
        description: 'Analizon sinjale EEG industriale, detekton evente',
        endpoints: ['/api/eeg-analysis-data'],
        status: 'active',
        metrics: ['analysisTimeMs', 'peak', 'mean', 'eventCount']
      },
      {
        name: 'Neuroacoustic Converter',
        type: 'krijuese',
        description: 'Konverton sinjale neuroakustike industriale',
        endpoints: ['/api/neuroacoustic-converter-data'],
        status: 'active',
        metrics: ['conversionTimeMs', 'inputPeak', 'outputPeak', 'snr']
      },
      {
        name: 'Spectrum Analyzer',
        type: 'studiuese',
        description: 'Analizues spektral industrial',
        endpoints: ['/api/spectrum-analyzer-data'],
        status: 'active',
        metrics: ['analysisTimeMs', 'peak', 'mean']
      },
      {
        name: 'Signal Generator',
        type: 'krijuese',
        description: 'Gjeneron sinjale industriale',
        endpoints: ['/api/signal-gen-data', '/api/signal-gen-status'],
        status: 'active',
        metrics: ['frequency', 'amplitude', 'waveform', 'duration', 'sampleRate']
      },
      {
        name: 'Backend Health',
        type: 'studiuese',
        description: 'Monitoron statusin industrial tÃ« backend-it',
        endpoints: ['/api/backend-health'],
        status: 'active',
        metrics: ['cpu', 'memory', 'requests', 'errors', 'auditEvents']
      }
    ],
    creativeFunctions: [
      'Sintetizim',
      'Konvertim',
      'Gjenerim sinjali'
    ],
    studyFunctions: [
      'AnalizÃ« EEG',
      'AnalizÃ« spektrale',
      'Monitorim industrial',
      'Audit',
      'Tracing',
      'Metrika'
    ]
  },
  industrialFeatures: {
    automatedTesting: {
      enabled: true,
      types: ['unit', 'integration', 'e2e'],
      tools: ['Jest', 'Playwright', 'Supertest'],
      coverage: '100% industrial required'
    },
    ciCd: {
      enabled: true,
      workflows: ['build', 'test', 'deploy', 'audit'],
      platforms: ['GitHub Actions', 'Azure Pipelines', 'Docker Hub']
    },
    backupRecovery: {
      enabled: true,
      strategy: 'daily, encrypted, offsite',
      scripts: ['backup.ps1', 'restore.ps1']
    },
    alertingIncident: {
      enabled: true,
      monitoring: ['Prometheus', 'Grafana', 'Docker stats'],
      alertChannels: ['email', 'slack', 'sms'],
      incidentResponse: 'automated & manual'
    },
    securityScanning: {
      enabled: true,
      tools: ['npm audit', 'Snyk', 'OWASP ZAP'],
      schedule: 'on build & weekly'
    },
    apiDocumentation: {
      enabled: true,
      format: ['OpenAPI', 'Swagger'],
      autoGenerated: true,
      location: '/api/docs'
    },
    userRoleManagement: {
      enabled: true,
      auth: ['JWT', 'OAuth2'],
      roles: ['admin', 'operator', 'auditor', 'user'],
      auditTrail: true
    },
    dataExportImport: {
      enabled: true,
      formats: ['JSON', 'CSV', 'XML'],
      security: 'encrypted, signed',
      endpoints: ['/api/export', '/api/import']
    },
    complianceReports: {
      enabled: true,
      standards: ['ISO-9001', 'GDPR', 'HIPAA'],
      autoGenerated: true,
      location: '/compliance/reports'
    },
    benchmarking: {
      enabled: true,
      scripts: ['benchmark.ps1', 'loadtest.js'],
      metrics: ['latency', 'throughput', 'errorRate'],
      required: 'monthly'
    }
  },
  experimental: {
    serverActions: true,
    optimizeCss: true,
    optimizeImages: true,
    instrumentationHook: true,
    logging: true
  },
  images: {
    domains: [
      'industrial.Clisonix.com',
    // Konfigurimi industrial importuar nga industrial.config.json
    industrialConfig,
      'cdn.Clisonix.com',
      'api.Clisonix.com',
      'cloud.Clisonix.com'
    ],
    formats: ['image/webp', 'image/avif']
  },
  async headers() {
    return [
      {
        source: '/(.*)',
        headers: [
          { key: 'X-Industrial-Audit', value: 'true' },
          { key: 'X-Industrial-Metrika', value: 'enabled' },
          { key: 'X-Industrial-Protection', value: 'active' },
          { key: 'X-Industrial-Compliance', value: 'Ultra-Industrial' },
          { key: 'X-Industrial-Polyphony', value: 'max' },
          { key: 'X-Industrial-Tracing', value: 'enabled' },
          { key: 'X-Industrial-Error-Handling', value: 'advanced' },
          { key: 'X-Industrial-Monitoring', value: 'active' }
        ]
      },
      {
        source: '/api/(.*)',
        headers: [
          { key: 'X-API-Module', value: 'true' },
          { key: 'X-API-Log', value: 'enabled' },
          { key: 'X-API-Audit', value: 'active' }
        ]
      }
    ]
  },
  async rewrites() {
    return [
      { source: '/dashboard', destination: '/modules' },
      { source: '/health', destination: '/api/backend-health' },
      { source: '/neural-synthesis', destination: '/api/neural-synthesis-data' },
      { source: '/eeg-analysis', destination: '/api/eeg-analysis-data' },
      { source: '/neuroacoustic-converter', destination: '/api/neuroacoustic-converter-data' },
      { source: '/spectrum-analyzer', destination: '/api/spectrum-analyzer-data' },
      { source: '/industrial-dashboard', destination: '/modules/industrial-dashboard' }
    ]
  },
  security: {
    headers: {
      contentSecurityPolicy: "default-src 'self'; img-src *; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline';",
      referrerPolicy: 'strict-origin-when-cross-origin',
      frameOptions: 'DENY',
      xssProtection: '1; mode=block',
      hsts: 'max-age=63072000; includeSubDomains; preload'
    }
  },
  logging: {
    level: 'info',
    audit: true,
    tracing: true,
    errorHandling: 'advanced',
    compliance: 'Ultra-Industrial'
  },
  monitoring: {
    enabled: true,
    metrics: true,
    audit: true,
    tracing: true
  },
  documentation: {
    author: 'Ledjan Ahmati',
    version: '2.0.0',
    compliance: 'Ultra-Industrial',
    modules: [
      'neural-synthesis',
      'eeg-analysis',
      'neuroacoustic-converter',
      'spectrum-analyzer',
      'industrial-dashboard'
    ],
    endpoints: [
      '/api/neural-synthesis-data',
      '/api/eeg-analysis-data',
      '/api/neuroacoustic-converter-data',
      '/api/spectrum-analyzer-data',
      '/api/backend-health',
      '/api/signal-gen-data',
      '/api/signal-gen-status'
    ]
  }
}

export default nextConfig
