#!/bin/bash
# CLISONIX CLOUD - INVESTOR DEMO SCRIPT

echo "🚀 CLISONIX CLOUD - LIVE DEMO"
echo "====================================="
echo ""
echo "✅ SYSTEM STATUS:"
echo "  • API Server: http://localhost:8000 (Uvicorn)"
echo "  • Frontend: http://localhost:3003 (Next.js)"
echo "  • Database: PostgreSQL + Redis"
echo ""
echo "📊 DEMO ENDPOINTS:"
echo ""
echo "1. CREATE USER PROFILE"
echo "   curl -X POST http://localhost:8000/fitness/users/profile \\"
echo "   -H 'Content-Type: application/json' \\"
echo "   -d '{\"name\": \"Demo User\", \"age\": 30, \"fitness_level\": \"Intermediate\"}'"
echo ""
echo "2. START WORKOUT"
echo "   curl -X POST http://localhost:8000/fitness/workouts/start \\"
echo "   -H 'Content-Type: application/json' \\"
echo "   -d '{\"user_id\": \"user-001\", \"workout_type\": \"STRENGTH\"}'"
echo ""
echo "3. RECORD BIOMETRIC"
echo "   curl -X POST http://localhost:8000/fitness/biometrics/record \\"
echo "   -H 'Content-Type: application/json' \\"
echo "   -d '{\"user_id\": \"user-001\", \"heart_rate\": 145, \"calories\": 250}'"
echo ""
echo "4. AI FORM ANALYSIS"
echo "   curl -X POST http://localhost:8000/fitness/coaching/analyze-form \\"
echo "   -H 'Content-Type: application/json' \\"
echo "   -d '{\"exercise_type\": \"PUSH_UPS\", \"joint_angles\": [90, 45], \"user_id\": \"user-001\"}'"
echo ""
echo "5. GET WORKOUT STATS"
echo "   curl http://localhost:8000/fitness/users/user-001/stats"
echo ""
echo "🎨 FRONTEND DEMO:"
echo "   • Dashboard: http://localhost:3003/modules/fitness-dashboard"
echo "   • EEG Analysis: http://localhost:3003/modules/eeg-analysis"
echo "   • Phone Monitor: http://localhost:3003/modules/phone-monitor"
echo ""
echo "📈 KEY FEATURES LIVE:"
echo "   ✓ Real-time biometric tracking"
echo "   ✓ AI form analysis for exercises"
echo "   ✓ Emotion & stress detection"
echo "   ✓ Neural feedback integration"
echo "   ✓ Dashboard with animations"
echo ""
echo "====================================="
echo "Demo prepared. Ready to impress investors! 🎯"
