openapi: 3.1.0
info:
  title: Alba API
  version: 1.0.0
  description: |
    Alba is Clisonix's content generation and creative workflow agent.
    
    **Features:**
    - Frame-by-frame animation generation
    - Content creation workflows
    - Creative asset management
    - Async task processing
    
    **Port:** 5555  
    **Health Check:** `GET /health`
  contact:
    name: Clisonix Engineering
    url: https://github.com/LedjanAhmati/Clisonix-cloud
  license:
    name: MIT
    
servers:
  - url: http://localhost:5555
    description: Development server
  - url: http://192.168.2.122:5555
    description: Local network
  - url: https://api.clisonix.com/alba
    description: Production server

tags:
  - name: Health
    description: Service health and status endpoints
  - name: Content Generation
    description: Creative content and animation generation
  - name: Workflows
    description: Multi-step creative workflows
  - name: Tasks
    description: Async task management

paths:
  /health:
    get:
      summary: Health check
      description: Returns service health status and metrics
      operationId: getHealth
      tags:
        - Health
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'
              example:
                status: healthy
                service: alba
                version: 1.0.0
                uptime_seconds: 3600
                tasks_processed: 1234
                
  /content/generate:
    post:
      summary: Generate content
      description: Creates new content based on provided parameters
      operationId: generateContent
      tags:
        - Content Generation
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContentRequest'
            example:
              type: animation
              style: modern
              duration: 30
              format: mp4
              parameters:
                resolution: 1920x1080
                fps: 60
      responses:
        '202':
          description: Content generation task accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '429':
          $ref: '#/components/responses/RateLimited'
          
  /frames/generate:
    post:
      summary: Generate animation frames
      description: Creates individual frames for animation sequences
      operationId: generateFrames
      tags:
        - Content Generation
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FrameRequest'
      responses:
        '202':
          description: Frame generation task accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
          
  /tasks/{task_id}:
    get:
      summary: Get task status
      description: Retrieves the status and result of an async task
      operationId: getTaskStatus
      tags:
        - Tasks
      security:
        - ApiKeyAuth: []
      parameters:
        - name: task_id
          in: path
          required: true
          description: Unique task identifier
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Task status retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskStatusResponse'
        '404':
          $ref: '#/components/responses/NotFound'
          
  /workflows/create:
    post:
      summary: Create workflow
      description: Initiates a multi-step creative workflow
      operationId: createWorkflow
      tags:
        - Workflows
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WorkflowRequest'
      responses:
        '201':
          description: Workflow created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkflowResponse'
        '400':
          $ref: '#/components/responses/BadRequest'

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
      description: Clisonix API key
      
  schemas:
    HealthResponse:
      type: object
      required:
        - status
        - service
        - version
      properties:
        status:
          type: string
          enum: [healthy, degraded, unhealthy]
        service:
          type: string
          example: alba
        version:
          type: string
          example: 1.0.0
        uptime_seconds:
          type: integer
          example: 3600
        tasks_processed:
          type: integer
          example: 1234
        error_rate:
          type: number
          format: float
          example: 0.02
          
    ContentRequest:
      type: object
      required:
        - type
        - format
      properties:
        type:
          type: string
          enum: [animation, image, video, audio]
        style:
          type: string
          example: modern
        duration:
          type: integer
          description: Duration in seconds (for video/animation)
          example: 30
        format:
          type: string
          enum: [mp4, webm, png, jpg, wav, mp3]
        parameters:
          type: object
          additionalProperties: true
          
    FrameRequest:
      type: object
      required:
        - count
        - resolution
      properties:
        count:
          type: integer
          minimum: 1
          maximum: 1000
          example: 60
        resolution:
          type: string
          pattern: '^\d+x\d+$'
          example: 1920x1080
        style:
          type: string
          example: cinematic
        scene_data:
          type: object
          additionalProperties: true
          
    WorkflowRequest:
      type: object
      required:
        - name
        - steps
      properties:
        name:
          type: string
          example: Product Launch Video
        steps:
          type: array
          items:
            type: object
            required:
              - action
            properties:
              action:
                type: string
                example: generate_frames
              parameters:
                type: object
                additionalProperties: true
                
    TaskResponse:
      type: object
      required:
        - task_id
        - status
      properties:
        task_id:
          type: string
          format: uuid
        status:
          type: string
          enum: [pending, processing, completed, failed]
        created_at:
          type: string
          format: date-time
        estimated_completion:
          type: string
          format: date-time
          
    TaskStatusResponse:
      type: object
      required:
        - task_id
        - status
      properties:
        task_id:
          type: string
          format: uuid
        status:
          type: string
          enum: [pending, processing, completed, failed]
        progress:
          type: number
          format: float
          minimum: 0
          maximum: 100
        result:
          type: object
          additionalProperties: true
        error:
          type: string
          
    WorkflowResponse:
      type: object
      required:
        - workflow_id
        - status
      properties:
        workflow_id:
          type: string
          format: uuid
        status:
          type: string
          enum: [created, running, completed, failed]
        steps_completed:
          type: integer
        total_steps:
          type: integer
          
    ErrorResponse:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          example: invalid_request
        message:
          type: string
          example: Missing required field 'type'
        details:
          type: object
          additionalProperties: true
          
  responses:
    BadRequest:
      description: Invalid request parameters
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    Unauthorized:
      description: Missing or invalid API key
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            error: unauthorized
            message: Invalid API key
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    RateLimited:
      description: Rate limit exceeded
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
      headers:
        X-RateLimit-Limit:
          schema:
            type: integer
          description: Request limit per hour
        X-RateLimit-Remaining:
          schema:
            type: integer
          description: Remaining requests in current window
        X-RateLimit-Reset:
          schema:
            type: integer
          description: Unix timestamp when limit resets
