openapi: 3.1.0
info:
  title: Albi API
  version: 1.0.0
  description: |
    Albi is Clisonix's data processing and analytics agent.
    
    **Features:**
    - Real-time pattern detection
    - Neural analytics processing
    - Business intelligence insights
    - Data correlation analysis
    
    **Port:** 6680  
    **Health Check:** `GET /health`
  contact:
    name: Clisonix Engineering
    url: https://github.com/LedjanAhmati/Clisonix-cloud
  license:
    name: MIT
    
servers:
  - url: http://localhost:6680
    description: Development server
  - url: http://192.168.2.122:6680
    description: Local network
  - url: https://api.clisonix.com/albi
    description: Production server

tags:
  - name: Health
    description: Service health and status endpoints
  - name: Analytics
    description: Data analytics and processing
  - name: Patterns
    description: Pattern detection and recognition
  - name: Insights
    description: Business intelligence insights

paths:
  /health:
    get:
      summary: Health check
      description: Returns service health status and metrics
      operationId: getHealth
      tags:
        - Health
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'
              example:
                status: healthy
                service: albi
                version: 1.0.0
                uptime_seconds: 7200
                events_processed: 5678
                
  /analytics/process:
    post:
      summary: Process analytics data
      description: Analyzes provided dataset and returns insights
      operationId: processAnalytics
      tags:
        - Analytics
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AnalyticsRequest'
            example:
              dataset_id: user_behavior_2025
              timeframe:
                start: 2025-01-01T00:00:00Z
                end: 2025-01-31T23:59:59Z
              metrics:
                - engagement_rate
                - conversion_rate
                - retention
      responses:
        '200':
          description: Analytics processed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnalyticsResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
          
  /patterns/detect:
    post:
      summary: Detect patterns
      description: Identifies patterns in time-series or event data
      operationId: detectPatterns
      tags:
        - Patterns
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatternRequest'
      responses:
        '200':
          description: Patterns detected
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PatternResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
          
  /insights/generate:
    post:
      summary: Generate insights
      description: Produces actionable business intelligence from data
      operationId: generateInsights
      tags:
        - Insights
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InsightRequest'
      responses:
        '200':
          description: Insights generated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InsightResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
          
  /correlations/analyze:
    post:
      summary: Analyze correlations
      description: Finds correlations between multiple data streams
      operationId: analyzeCorrelations
      tags:
        - Analytics
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CorrelationRequest'
      responses:
        '200':
          description: Correlations analyzed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CorrelationResponse'

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
      description: Clisonix API key
      
  schemas:
    HealthResponse:
      type: object
      required:
        - status
        - service
        - version
      properties:
        status:
          type: string
          enum: [healthy, degraded, unhealthy]
        service:
          type: string
          example: albi
        version:
          type: string
          example: 1.0.0
        uptime_seconds:
          type: integer
          example: 7200
        events_processed:
          type: integer
          example: 5678
        queue_depth:
          type: integer
          example: 12
          
    AnalyticsRequest:
      type: object
      required:
        - dataset_id
      properties:
        dataset_id:
          type: string
          example: user_behavior_2025
        timeframe:
          type: object
          properties:
            start:
              type: string
              format: date-time
            end:
              type: string
              format: date-time
        metrics:
          type: array
          items:
            type: string
          example: [engagement_rate, conversion_rate]
        filters:
          type: object
          additionalProperties: true
          
    AnalyticsResponse:
      type: object
      required:
        - dataset_id
        - results
      properties:
        dataset_id:
          type: string
        results:
          type: object
          additionalProperties: true
        summary:
          type: object
          properties:
            total_records:
              type: integer
            time_range:
              type: string
            key_metrics:
              type: object
              additionalProperties: true
              
    PatternRequest:
      type: object
      required:
        - data
        - detection_type
      properties:
        data:
          type: array
          items:
            type: object
            additionalProperties: true
        detection_type:
          type: string
          enum: [anomaly, trend, seasonality, clustering]
        sensitivity:
          type: number
          format: float
          minimum: 0
          maximum: 1
          example: 0.8
          
    PatternResponse:
      type: object
      required:
        - patterns_found
      properties:
        patterns_found:
          type: integer
        patterns:
          type: array
          items:
            type: object
            properties:
              type:
                type: string
              confidence:
                type: number
                format: float
              details:
                type: object
                additionalProperties: true
                
    InsightRequest:
      type: object
      required:
        - source
        - insight_type
      properties:
        source:
          type: string
          description: Data source identifier
        insight_type:
          type: string
          enum: [predictive, descriptive, prescriptive]
        context:
          type: object
          additionalProperties: true
          
    InsightResponse:
      type: object
      required:
        - insights
      properties:
        insights:
          type: array
          items:
            type: object
            properties:
              category:
                type: string
              priority:
                type: string
                enum: [critical, high, medium, low]
              description:
                type: string
              recommendation:
                type: string
              confidence:
                type: number
                format: float
                
    CorrelationRequest:
      type: object
      required:
        - streams
      properties:
        streams:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              data:
                type: array
                items:
                  type: number
        method:
          type: string
          enum: [pearson, spearman, kendall]
          default: pearson
          
    CorrelationResponse:
      type: object
      required:
        - correlations
      properties:
        correlations:
          type: array
          items:
            type: object
            properties:
              stream_a:
                type: string
              stream_b:
                type: string
              coefficient:
                type: number
                format: float
              p_value:
                type: number
                format: float
              significance:
                type: string
                enum: [high, medium, low, none]
                
    ErrorResponse:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
        message:
          type: string
        details:
          type: object
          additionalProperties: true
          
  responses:
    BadRequest:
      description: Invalid request parameters
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    Unauthorized:
      description: Missing or invalid API key
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    RateLimited:
      description: Rate limit exceeded
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
      headers:
        X-RateLimit-Limit:
          schema:
            type: integer
        X-RateLimit-Remaining:
          schema:
            type: integer
        X-RateLimit-Reset:
          schema:
            type: integer

