openapi: 3.1.0
info:
  title: Jona API
  version: 1.0.0
  description: |
    Jona is Clisonix's coordination and neural audio generation agent.
    
    **Features:**
    - Data synthesis and transformation
    - Neural audio generation (EEG to audio)
    - Multi-modal signal processing
    - Real-time audio streaming
    
    **Port:** 7777  
    **Health Check:** `GET /health`
  contact:
    name: Clisonix Engineering
    url: https://github.com/LedjanAhmati/Clisonix-cloud
  license:
    name: MIT
    
servers:
  - url: http://localhost:7777
    description: Development server
  - url: http://192.168.2.122:7777
    description: Local network
  - url: https://api.clisonix.com/jona
    description: Production server

tags:
  - name: Health
    description: Service health and status endpoints
  - name: Audio Generation
    description: Neural audio synthesis from EEG signals
  - name: Signal Processing
    description: Multi-modal signal analysis
  - name: Synthesis
    description: Data synthesis and transformation
  - name: Streaming
    description: Real-time audio streaming

paths:
  /health:
    get:
      summary: Health check
      description: Returns service health status and metrics
      operationId: getHealth
      tags:
        - Health
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'
              example:
                status: healthy
                service: jona
                version: 1.0.0
                uptime_seconds: 4500
                audio_files_generated: 892
                
  /audio/generate:
    post:
      summary: Generate neural audio
      description: Creates audio from EEG signal data
      operationId: generateAudio
      tags:
        - Audio Generation
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AudioRequest'
            example:
              signal_type: eeg
              channels: 8
              duration: 60
              output_format: wav
              parameters:
                sample_rate: 44100
                bit_depth: 16
                mood: calm
      responses:
        '202':
          description: Audio generation task accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
          
  /audio/upload:
    post:
      summary: Upload EEG data
      description: Uploads raw EEG signal files for processing
      operationId: uploadEEG
      tags:
        - Audio Generation
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - file
              properties:
                file:
                  type: string
                  format: binary
                  description: EEG data file (.edf, .bdf, .csv)
                metadata:
                  type: object
                  description: Optional metadata (JSON string)
      responses:
        '201':
          description: File uploaded successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UploadResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '413':
          description: File too large
          
  /audio/stream/{session_id}:
    get:
      summary: Stream audio
      description: Real-time audio streaming from active session
      operationId: streamAudio
      tags:
        - Streaming
      security:
        - ApiKeyAuth: []
      parameters:
        - name: session_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Audio stream
          content:
            audio/wav:
              schema:
                type: string
                format: binary
        '404':
          $ref: '#/components/responses/NotFound'
          
  /signals/process:
    post:
      summary: Process signal data
      description: Analyzes and transforms multi-modal signal data
      operationId: processSignals
      tags:
        - Signal Processing
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignalRequest'
      responses:
        '200':
          description: Signals processed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignalResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
          
  /synthesis/create:
    post:
      summary: Create data synthesis
      description: Synthesizes new data based on patterns and inputs
      operationId: createSynthesis
      tags:
        - Synthesis
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SynthesisRequest'
      responses:
        '200':
          description: Synthesis created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SynthesisResponse'
                
  /tasks/{task_id}:
    get:
      summary: Get task status
      description: Retrieves status of audio generation task
      operationId: getTaskStatus
      tags:
        - Audio Generation
      security:
        - ApiKeyAuth: []
      parameters:
        - name: task_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Task status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskStatusResponse'
        '404':
          $ref: '#/components/responses/NotFound'

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
      description: Clisonix API key
      
  schemas:
    HealthResponse:
      type: object
      required:
        - status
        - service
        - version
      properties:
        status:
          type: string
          enum: [healthy, degraded, unhealthy]
        service:
          type: string
          example: jona
        version:
          type: string
          example: 1.0.0
        uptime_seconds:
          type: integer
          example: 4500
        audio_files_generated:
          type: integer
          example: 892
        active_streams:
          type: integer
          example: 3
          
    AudioRequest:
      type: object
      required:
        - signal_type
        - duration
      properties:
        signal_type:
          type: string
          enum: [eeg, ecg, emg, generic]
        channels:
          type: integer
          minimum: 1
          maximum: 256
          example: 8
        duration:
          type: integer
          description: Duration in seconds
          minimum: 1
          maximum: 600
          example: 60
        output_format:
          type: string
          enum: [wav, mp3, flac, ogg]
          default: wav
        parameters:
          type: object
          properties:
            sample_rate:
              type: integer
              enum: [22050, 44100, 48000, 96000]
            bit_depth:
              type: integer
              enum: [16, 24, 32]
            mood:
              type: string
              enum: [calm, energetic, meditative, focus]
          additionalProperties: true
          
    UploadResponse:
      type: object
      required:
        - file_id
        - status
      properties:
        file_id:
          type: string
          format: uuid
        status:
          type: string
          enum: [uploaded, processing]
        filename:
          type: string
        size_bytes:
          type: integer
        channels_detected:
          type: integer
        duration_seconds:
          type: number
          format: float
          
    SignalRequest:
      type: object
      required:
        - data
        - processing_type
      properties:
        data:
          type: array
          items:
            type: array
            items:
              type: number
          description: Multi-channel signal data (channels x samples)
        processing_type:
          type: string
          enum: [filter, normalize, denoise, transform]
        parameters:
          type: object
          additionalProperties: true
          
    SignalResponse:
      type: object
      required:
        - processed_data
      properties:
        processed_data:
          type: array
          items:
            type: array
            items:
              type: number
        metadata:
          type: object
          properties:
            channels:
              type: integer
            samples:
              type: integer
            transformations_applied:
              type: array
              items:
                type: string
                
    SynthesisRequest:
      type: object
      required:
        - synthesis_type
      properties:
        synthesis_type:
          type: string
          enum: [audio, signal, hybrid]
        source_data:
          type: object
          additionalProperties: true
        parameters:
          type: object
          additionalProperties: true
          
    SynthesisResponse:
      type: object
      required:
        - result_id
        - data
      properties:
        result_id:
          type: string
          format: uuid
        data:
          type: object
          additionalProperties: true
        metadata:
          type: object
          additionalProperties: true
          
    TaskResponse:
      type: object
      required:
        - task_id
        - status
      properties:
        task_id:
          type: string
          format: uuid
        status:
          type: string
          enum: [pending, processing, completed, failed]
        created_at:
          type: string
          format: date-time
        estimated_completion:
          type: string
          format: date-time
          
    TaskStatusResponse:
      type: object
      required:
        - task_id
        - status
      properties:
        task_id:
          type: string
          format: uuid
        status:
          type: string
          enum: [pending, processing, completed, failed]
        progress:
          type: number
          format: float
          minimum: 0
          maximum: 100
        result:
          type: object
          properties:
            audio_url:
              type: string
              format: uri
            format:
              type: string
            duration:
              type: number
        error:
          type: string
          
    ErrorResponse:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
        message:
          type: string
        details:
          type: object
          additionalProperties: true
          
  responses:
    BadRequest:
      description: Invalid request parameters
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    Unauthorized:
      description: Missing or invalid API key
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    RateLimited:
      description: Rate limit exceeded
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
      headers:
        X-RateLimit-Limit:
          schema:
            type: integer
        X-RateLimit-Remaining:
          schema:
            type: integer
        X-RateLimit-Reset:
          schema:
            type: integer
